---
- name: Download and Add New-Relic Key to Apt-Get Keyring
  apt_key: url=https://download.newrelic.com/548C16BF.gpg state=present

- name: Add New-Relic Repository into /etc/apt/sources.list
  apt_repository: repo='deb http://apt.newrelic.com/debian/ newrelic non-free' state=present

- name: Update Cache
  apt: update_cache=yes force=yes

- name: Install New Relic Server Monitor Package
  apt: pkg=newrelic-sysmond state=latest force=yes
  register: newrelic

- name: Set License Key
  command: "nrsysmond-config --set license_key={{ new_relic_license_key }}"

- name: Restart New Relic
  service: name="newrelic-sysmond" state="restarted"
  when: newrelic.changed
