---
- name: Enable UFW
  ufw: state=enabled

- name: Rate Limit Port 22
  ufw: rule=limit port=22 proto=tcp

- name: Allow Port 80
  ufw: rule=allow port=80 proto=tcp

- name: Allow Port 443
  ufw: rule=allow port=443 proto=tcp

- name: Default Deny Incoming
  ufw: direction=incoming policy=deny

- name: Enable UFW Logging
  ufw: logging=medium
