---
- name: Download and Add NGINX Key to Apt-Get Keyring
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present

- name: Add NGINX Repository into /etc/apt/sources.list
  apt_repository: repo='deb http://nginx.org/packages/mainline/ubuntu/ utopic nginx' state=present
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'utopic'

- name: Add NGINX Repository into /etc/apt/sources.list
  apt_repository: repo='deb http://nginx.org/packages/mainline/ubuntu/ vivid nginx' state=present
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'vivid'

- name: Install NGINX Package
  apt: pkg=nginx state=latest
  register: nginx_installed

- name: Start the NGINX Service
  service: name=nginx state=started enabled=yes
